"""Postgres (Supabase) storage — asyncpg implementation mirroring db_sqlite's public API.

Same function names / signatures / return shapes as ``db_sqlite`` so the rest of the app
(bot, api, persist) is backend-agnostic: ``local/db.py`` dispatches to this module when
``config.DB_BACKEND == "postgres"``. asyncpg ``Record`` supports ``dict(r)``, ``r[0]`` and
``r["col"]``, so result handling matches the SQLite code.

Pure, dialect-independent helpers/constants (COLLECTIONS, business-model numbers, is_pro,
_collection_clause, _hunt_criteria) are reused from db_sqlite to avoid drift.
"""
from __future__ import annotations

import datetime as dt
import random
import ssl
from contextlib import asynccontextmanager
from typing import Any, Dict, List, Optional, Tuple

import asyncpg

from local import config
from local.plate import parse_plate
# Reuse pure (SQL-dialect-independent) pieces so business logic stays in one place.
from local.db_sqlite import (  # noqa: F401  (re-exported via local/db.py star import)
    COLLECTIONS, BASE_FREE_HUNTS, SHARE_BONUS_HUNTS, FRIENDS_PER_HUNT,
    PRO_INVITE_THRESHOLD, PRO_DAYS_FOR_INVITES, SEARCH_LIMIT_PER_DAY,
    is_pro, _collection_clause, _hunt_criteria,
)

_pool: Optional[asyncpg.Pool] = None

# In-memory TTL cache for hot, slowly-changing reads (stats, dictionaries, collection counts).
# Aggregates over the full plates table are expensive on a remote DB, so we memoise them.
import time as _time

_CACHE: Dict[str, Any] = {}


def invalidate_cache() -> None:
    """Drop all cached reads (call after a scan/commit changes the data)."""
    _CACHE.clear()


async def warm_cache() -> None:
    """Pre-compute the hot cached reads so the first user doesn't pay the cold cost."""
    try:
        await get_stats()
        await distinct_regions()
        await distinct_vehicle_types()
        await collection_counts()
    except Exception:  # noqa: BLE001
        pass


async def _memo(key: str, ttl: float, fn):
    """Return a cached value for ``key`` (recompute via ``fn`` when stale)."""
    now = _time.monotonic()
    e = _CACHE.get(key)
    if e and now - e[0] < ttl:
        return e[1]
    val = await fn()
    _CACHE[key] = (now, val)
    return val


def _now() -> str:
    """UTC ISO timestamp string (matches db_sqlite so migrated rows compare correctly)."""
    return dt.datetime.now(dt.timezone.utc).isoformat()


def _cutoff(days: int) -> str:
    """ISO timestamp ``days`` in the past — used for time-window filters on TEXT timestamps."""
    return (dt.datetime.now(dt.timezone.utc) - dt.timedelta(days=days)).isoformat()


def _q(sql: str) -> str:
    """Convert SQLite-style ``?`` placeholders to Postgres ``$1, $2, …`` (no literal ? in our SQL)."""
    out: List[str] = []
    i = 0
    for ch in sql:
        if ch == "?":
            i += 1
            out.append(f"${i}")
        else:
            out.append(ch)
    return "".join(out)


def _rowcount(status: str) -> int:
    """Parse asyncpg command status like 'DELETE 5' / 'UPDATE 3' → affected row count."""
    try:
        return int(status.split()[-1])
    except (ValueError, IndexError):
        return 0


async def _get_pool() -> asyncpg.Pool:
    """Lazily create the connection pool (SSL required by Supabase)."""
    global _pool
    if _pool is None:
        ctx = ssl.create_default_context()
        ctx.check_hostname = False
        ctx.verify_mode = ssl.CERT_NONE  # encrypt in transit; Supabase pooler cert not verified
        _pool = await asyncpg.create_pool(
            host=config.PG_HOST, port=config.PG_PORT, database=config.PG_DB,
            user=config.PG_USER, password=config.PG_PASSWORD, ssl=ctx,
            min_size=1, max_size=8, command_timeout=60, statement_cache_size=0,
        )
    return _pool


async def _fetch(sql: str, *args: Any) -> List[asyncpg.Record]:
    pool = await _get_pool()
    async with pool.acquire() as c:
        return await c.fetch(_q(sql), *args)


async def _fetchrow(sql: str, *args: Any) -> Optional[asyncpg.Record]:
    pool = await _get_pool()
    async with pool.acquire() as c:
        return await c.fetchrow(_q(sql), *args)


async def _fetchval(sql: str, *args: Any) -> Any:
    pool = await _get_pool()
    async with pool.acquire() as c:
        return await c.fetchval(_q(sql), *args)


async def _exec(sql: str, *args: Any) -> str:
    pool = await _get_pool()
    async with pool.acquire() as c:
        return await c.execute(_q(sql), *args)


# Schema for a fresh deploy (idempotent). The bulk migration is done by local.migrate_to_pg.
_SCHEMA = """
CREATE TABLE IF NOT EXISTS plates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plate_number TEXT NOT NULL, letters_start TEXT, letters_end TEXT, digits TEXT,
    digits_int BIGINT, region TEXT NOT NULL, tsc TEXT, vehicle_type TEXT, price DOUBLE PRECISION,
    is_available INTEGER DEFAULT 1, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL,
    removed_at TEXT, UNIQUE (plate_number, tsc, vehicle_type));
CREATE INDEX IF NOT EXISTS idx_plates_number ON plates(plate_number);
CREATE INDEX IF NOT EXISTS idx_plates_region ON plates(region);
CREATE INDEX IF NOT EXISTS idx_plates_digits ON plates(digits);
CREATE INDEX IF NOT EXISTS idx_plates_ls ON plates(letters_start);
CREATE INDEX IF NOT EXISTS idx_plates_avail ON plates(is_available);
CREATE TABLE IF NOT EXISTS users (
    chat_id BIGINT PRIMARY KEY, username TEXT, created_at TEXT NOT NULL, referred_by BIGINT,
    invited_count INTEGER DEFAULT 0, bonus_hunts INTEGER DEFAULT 0, plan TEXT DEFAULT 'free',
    plan_until TEXT, shared INTEGER DEFAULT 0, searches_today INTEGER DEFAULT 0,
    searches_date TEXT, phone TEXT, is_bot INTEGER DEFAULT 0);
CREATE TABLE IF NOT EXISTS hunts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT NOT NULL, name TEXT,
    match_type TEXT NOT NULL, pattern TEXT, letters_start TEXT, letters_end TEXT,
    digits_exact TEXT, digits_contains TEXT, digits_mask TEXT, region TEXT, vehicle_type TEXT,
    price_min DOUBLE PRECISION, price_max DOUBLE PRECISION, is_active INTEGER DEFAULT 1,
    created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_hunts_chat ON hunts(chat_id);
CREATE TABLE IF NOT EXISTS notified (
    hunt_id BIGINT NOT NULL, plate_id BIGINT NOT NULL, created_at TEXT NOT NULL,
    PRIMARY KEY (hunt_id, plate_id));
CREATE TABLE IF NOT EXISTS favorites (
    chat_id BIGINT NOT NULL, plate_number TEXT NOT NULL, digits TEXT, region TEXT,
    created_at TEXT NOT NULL, PRIMARY KEY (chat_id, plate_number));
CREATE INDEX IF NOT EXISTS idx_fav_plate ON favorites(plate_number);
CREATE INDEX IF NOT EXISTS idx_fav_digits ON favorites(digits);
CREATE TABLE IF NOT EXISTS tsc (
    code TEXT PRIMARY KEY, region TEXT, name TEXT, address TEXT, city TEXT,
    lat DOUBLE PRECISION, lon DOUBLE PRECISION);
CREATE TABLE IF NOT EXISTS admins (chat_id BIGINT PRIMARY KEY, added_by BIGINT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS error_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT, username TEXT,
    text TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS notif_messages (chat_id BIGINT NOT NULL, message_id BIGINT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_notifmsg_chat ON notif_messages(chat_id);
CREATE TABLE IF NOT EXISTS search_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, chat_id BIGINT, username TEXT,
    summary TEXT, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_searchlog_created ON search_log(created_at);
CREATE TABLE IF NOT EXISTS feed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, plate_number TEXT NOT NULL,
    region TEXT, vehicle_type TEXT, event TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_feed_evt ON feed_events(event, created_at);
CREATE TABLE IF NOT EXISTS meta (key TEXT PRIMARY KEY, value TEXT);
CREATE TABLE IF NOT EXISTS app_link (
    code TEXT PRIMARY KEY, chat_id BIGINT, token TEXT, status TEXT DEFAULT 'pending',
    created_at TEXT NOT NULL);
CREATE INDEX IF NOT EXISTS idx_applink_token ON app_link(token);
"""


async def init_db() -> None:
    """Ensure the schema exists (no-op if migration already created it)."""
    pool = await _get_pool()
    async with pool.acquire() as c:
        await c.execute(_SCHEMA)


@asynccontextmanager
async def acquire():
    """Yield a transactional connection (commits on clean exit) for multi-step scan writes."""
    pool = await _get_pool()
    async with pool.acquire() as conn:
        tr = conn.transaction()
        await tr.start()
        try:
            yield conn
            await tr.commit()
        except Exception:
            await tr.rollback()
            raise


# ── scan persistence (connection passed in by persist.py) ──
async def upsert_plate(
    conn: asyncpg.Connection, plate_number: str, region: str, tsc: str,
    vehicle_type: Optional[str], price: Optional[float],
) -> Tuple[int, bool]:
    """Insert or refresh a plate. Returns (plate_id, is_new)."""
    parts = parse_plate(plate_number)
    now = _now()
    row = await conn.fetchrow(
        "SELECT id, is_available FROM plates WHERE plate_number=$1 "
        "AND tsc IS NOT DISTINCT FROM $2 AND vehicle_type IS NOT DISTINCT FROM $3",
        parts["plate_number"], tsc, vehicle_type,
    )
    if row is None:
        pid = await conn.fetchval(
            "INSERT INTO plates (plate_number, letters_start, letters_end, digits, digits_int, "
            "region, tsc, vehicle_type, price, is_available, first_seen_at, last_seen_at) "
            "VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,1,$10,$10) RETURNING id",
            parts["plate_number"], parts["letters_start"], parts["letters_end"],
            parts["digits"], parts["digits_int"], region, tsc, vehicle_type, price, now,
        )
        return int(pid), True
    await conn.execute(
        "UPDATE plates SET is_available=1, removed_at=NULL, last_seen_at=$1, price=$2 WHERE id=$3",
        now, price, row["id"],
    )
    return int(row["id"]), not bool(row["is_available"])


async def bulk_upsert_plates(conn: asyncpg.Connection, rows: List[Dict[str, Any]], now: str = None) -> List[Dict[str, Any]]:
    """Batched insert/refresh of many plates in few round trips (vs per-row).

    Returns one dict per upserted row: {id, plate_number, region, vehicle_type, inserted}
    where ``inserted`` is True for brand-new plates (xmax=0). Far faster than upsert_plate
    for large batches over a remote DB.
    """
    now = now or _now()
    # De-dup on the unique key so a single statement never touches a row twice.
    uniq: Dict[tuple, Dict[str, Any]] = {}
    for r in rows:
        parts = parse_plate(r["plate_number"])
        key = (parts["plate_number"], r.get("tsc"), r.get("vehicle_type"))
        uniq[key] = (parts, r)
    items = list(uniq.values())
    out: List[Dict[str, Any]] = []
    BATCH = 1000
    sql = (
        "INSERT INTO plates (plate_number,letters_start,letters_end,digits,digits_int,region,"
        "tsc,vehicle_type,price,is_available,first_seen_at,last_seen_at) "
        "SELECT pn,ls,le,dg,di,rg,ts,vt,pr,1,$10,$10 FROM unnest("
        "$1::text[],$2::text[],$3::text[],$4::text[],$5::bigint[],$6::text[],$7::text[],$8::text[],$9::float8[]) "
        "AS t(pn,ls,le,dg,di,rg,ts,vt,pr) "
        "ON CONFLICT (plate_number, tsc, vehicle_type) DO UPDATE SET "
        "is_available=1, removed_at=NULL, last_seen_at=EXCLUDED.last_seen_at, price=EXCLUDED.price "
        "RETURNING id, plate_number, region, vehicle_type, (xmax=0) AS inserted"
    )
    for i in range(0, len(items), BATCH):
        chunk = items[i:i + BATCH]
        pn = [p["plate_number"] for p, _ in chunk]
        ls = [p["letters_start"] for p, _ in chunk]
        le = [p["letters_end"] for p, _ in chunk]
        dg = [p["digits"] for p, _ in chunk]
        di = [p["digits_int"] for p, _ in chunk]
        rg = [r["region"] for _, r in chunk]
        ts = [r.get("tsc") for _, r in chunk]
        vt = [r.get("vehicle_type") for _, r in chunk]
        pr = [r.get("price") for _, r in chunk]
        recs = await conn.fetch(sql, pn, ls, le, dg, di, rg, ts, vt, pr, now)
        for rec in recs:
            out.append({"id": rec["id"], "plate_number": rec["plate_number"], "region": rec["region"],
                        "vehicle_type": rec["vehicle_type"], "inserted": rec["inserted"]})
    return out


async def mark_removed(
    conn: asyncpg.Connection, region: str, vehicle_type: Optional[str], seen_ids: List[int]
) -> List[Dict[str, Any]]:
    """Mark available plates of a scope not in seen_ids as removed; return the removed rows."""
    now = _now()
    rows = await conn.fetch(
        "SELECT id, plate_number, region, vehicle_type FROM plates "
        "WHERE region=$1 AND vehicle_type IS NOT DISTINCT FROM $2 "
        "AND is_available=1 AND NOT (id = ANY($3::bigint[]))",
        region, vehicle_type, list(seen_ids),
    )
    removed = [dict(r) for r in rows]
    if removed:
        ids = [r["id"] for r in removed]
        await conn.execute(
            "UPDATE plates SET is_available=0, removed_at=$1 WHERE id = ANY($2::bigint[])", now, ids
        )
    return removed


async def reconcile_removed(conn: asyncpg.Connection) -> int:
    """Cancel 'removed' feed events for plates that are currently available again."""
    status = await conn.execute(
        "DELETE FROM feed_events WHERE event='removed' AND plate_number IN "
        "(SELECT plate_number FROM plates WHERE is_available=1)"
    )
    return _rowcount(status)


async def log_feed_event(
    conn: asyncpg.Connection, plate_number: str, region: str,
    vehicle_type: Optional[str], event: str,
) -> None:
    """Record a 'new' or 'removed' feed event (called per scan)."""
    await conn.execute(
        "INSERT INTO feed_events (plate_number, region, vehicle_type, event, created_at) "
        "VALUES ($1,$2,$3,$4,$5)",
        plate_number, region, vehicle_type, event, _now(),
    )


async def log_feed_events_bulk(conn: asyncpg.Connection, events: List[tuple]) -> None:
    """Insert many feed events in one statement. events = [(plate, region, vehicle_type, event), …]."""
    if not events:
        return
    now = _now()
    await conn.execute(
        "INSERT INTO feed_events (plate_number, region, vehicle_type, event, created_at) "
        "SELECT p, r, v, e, $5 FROM unnest($1::text[],$2::text[],$3::text[],$4::text[]) AS t(p,r,v,e)",
        [e[0] for e in events], [e[1] for e in events], [e[2] for e in events],
        [e[3] for e in events], now,
    )


async def upsert_tsc_region(conn: asyncpg.Connection, code: str, region: str) -> None:
    """Record the region for a TSC code (address filled later by the directory builder)."""
    await conn.execute(
        "INSERT INTO tsc (code, region) VALUES ($1,$2) "
        "ON CONFLICT (code) DO UPDATE SET region=excluded.region",
        code, region,
    )


async def active_hunts(conn: asyncpg.Connection) -> List[Dict[str, Any]]:
    """All active hunts (for matching during a scan)."""
    rows = await conn.fetch("SELECT * FROM hunts WHERE is_active=1")
    return [dict(r) for r in rows]


async def already_notified(conn: asyncpg.Connection, hunt_id: int, plate_id: int) -> bool:
    """Whether this hunt was already notified about this plate."""
    return await conn.fetchval(
        "SELECT 1 FROM notified WHERE hunt_id=$1 AND plate_id=$2", hunt_id, plate_id
    ) is not None


async def record_notified(conn: asyncpg.Connection, hunt_id: int, plate_id: int) -> None:
    """Record that a notification was sent."""
    await conn.execute(
        "INSERT INTO notified (hunt_id, plate_id, created_at) VALUES ($1,$2,$3) "
        "ON CONFLICT DO NOTHING",
        hunt_id, plate_id, _now(),
    )


async def get_plate(conn: asyncpg.Connection, plate_id: int) -> Optional[Dict[str, Any]]:
    """Fetch a plate row by id."""
    row = await conn.fetchrow("SELECT * FROM plates WHERE id=$1", plate_id)
    return dict(row) if row else None


# ── search / browse (pooled, one statement each) ──
async def search_plates(query: str, limit: int = 20, only_available: bool = True) -> List[Dict[str, Any]]:
    """Search plates by normalised substring of the plate number."""
    from local.plate import normalize_plate

    q = "%" + normalize_plate(query) + "%"
    sql = (
        "SELECT p.plate_number, p.region, p.tsc, p.vehicle_type, p.price, p.is_available, "
        "t.address AS tsc_address FROM plates p LEFT JOIN tsc t ON p.tsc = t.code "
        "WHERE p.plate_number LIKE ?"
    )
    if only_available:
        sql += " AND p.is_available=1"
    sql += " ORDER BY p.price IS NULL, p.price LIMIT ?"
    return [dict(r) for r in await _fetch(sql, q, limit)]


async def distinct_regions() -> List[str]:
    """Regions that have plates, sorted (cached — changes rarely)."""
    return await _memo("regions", 3600, _distinct_regions_raw)


async def _distinct_regions_raw() -> List[str]:
    return [r[0] for r in await _fetch("SELECT DISTINCT region FROM plates ORDER BY region")]


async def distinct_vehicle_types() -> List[str]:
    """Distinct vehicle types present, sorted (cached)."""
    return await _memo("vtypes", 3600, _distinct_vehicle_types_raw)


async def _distinct_vehicle_types_raw() -> List[str]:
    return [r[0] for r in await _fetch(
        "SELECT DISTINCT vehicle_type FROM plates WHERE vehicle_type IS NOT NULL ORDER BY vehicle_type"
    )]


async def collection_counts() -> List[Dict[str, Any]]:
    """Curated collections with counts (cached — heavy aggregates over the full table)."""
    async def fn():
        out = []
        for k, v in COLLECTIONS.items():
            out.append({"key": k, "label": v, "count": await count_filtered(collection=k)})
        return out
    return await _memo("colcounts", 900, fn)


async def distinct_prices(
    region: Optional[str] = None, tsc: Optional[str] = None,
    vehicle_type: Optional[str] = None, limit: int = 60,
) -> List[float]:
    """Distinct available prices for the given filters, ascending."""
    where = ["price IS NOT NULL", "is_available = 1"]
    params: List[Any] = []
    if region:
        where.append("region = ?")
        params.append(region)
    if tsc:
        where.append("tsc = ?")
        params.append(tsc)
    if vehicle_type:
        where.append("vehicle_type = ?")
        params.append(vehicle_type)
    params.append(limit)
    sql = "SELECT DISTINCT price FROM plates WHERE " + " AND ".join(where) + " ORDER BY price LIMIT ?"
    return [float(r[0]) for r in await _fetch(sql, *params)]


async def popular_combos(limit: int = 10) -> List[Dict[str, Any]]:
    """Most-favorited digit combinations."""
    return [dict(r) for r in await _fetch(
        "SELECT digits, COUNT(DISTINCT chat_id) c FROM favorites "
        "WHERE digits IS NOT NULL GROUP BY digits ORDER BY c DESC LIMIT ?", limit,
    )]


async def distinct_series(
    region: Optional[str] = None, vehicle_type: Optional[str] = None, limit: int = 60
) -> List[str]:
    """Distinct plate series (letters_start) for the given filters, by frequency."""
    where = ["letters_start IS NOT NULL", "is_available = 1"]
    params: List[Any] = []
    if region:
        where.append("region = ?")
        params.append(region)
    if vehicle_type:
        where.append("vehicle_type = ?")
        params.append(vehicle_type)
    params.append(limit)
    sql = ("SELECT letters_start, COUNT(*) c FROM plates WHERE " + " AND ".join(where)
           + " GROUP BY letters_start ORDER BY c DESC LIMIT ?")
    return [r[0] for r in await _fetch(sql, *params)]


async def tsc_for_region(region: str) -> List[Dict[str, Any]]:
    """TSC codes (with city) for a region, sorted by code."""
    return [dict(r) for r in await _fetch(
        "SELECT code, city FROM tsc WHERE region=? ORDER BY code", region
    )]


async def search_filtered(
    query: Optional[str] = None, region: Optional[str] = None, tsc: Optional[str] = None,
    vehicle_type: Optional[str] = None, letters_start: Optional[str] = None,
    price_min: Optional[float] = None, price_max: Optional[float] = None,
    collection: Optional[str] = None, limit: int = 15, offset: int = 0, only_available: bool = True,
) -> List[Dict[str, Any]]:
    """Search plates with optional text query + region/tsc/series/type/price/collection filters."""
    from local.plate import to_search_like

    where: List[str] = []
    params: List[Any] = []
    if collection:
        where.append(_collection_clause(collection, "p."))
    if query:
        mode, pattern = to_search_like(query)
        where.append("p.digits LIKE ?" if mode == "digits" else "p.plate_number LIKE ?")
        params.append(pattern)
    if region:
        where.append("p.region = ?")
        params.append(region)
    if tsc:
        where.append("p.tsc = ?")
        params.append(tsc)
    if letters_start:
        where.append("p.letters_start = ?")
        params.append(letters_start)
    if vehicle_type:
        where.append("p.vehicle_type = ?")
        params.append(vehicle_type)
    if price_min is not None:
        where.append("p.price >= ?")
        params.append(price_min)
    if price_max is not None:
        where.append("p.price <= ?")
        params.append(price_max)
    if only_available:
        where.append("p.is_available = 1")
    where_sql = (" WHERE " + " AND ".join(where)) if where else ""
    params.append(limit)
    params.append(offset)
    sql = (
        "SELECT p.plate_number, p.region, p.tsc, p.vehicle_type, p.price, p.is_available, "
        "t.address AS tsc_address FROM plates p LEFT JOIN tsc t ON p.tsc = t.code"
        + where_sql + " ORDER BY p.price IS NULL, p.price, p.plate_number LIMIT ? OFFSET ?"
    )
    return [dict(r) for r in await _fetch(sql, *params)]


async def count_filtered(
    query: Optional[str] = None, region: Optional[str] = None, tsc: Optional[str] = None,
    vehicle_type: Optional[str] = None, letters_start: Optional[str] = None,
    price_min: Optional[float] = None, price_max: Optional[float] = None,
    collection: Optional[str] = None, only_available: bool = True,
) -> int:
    """Count plates matching the same filters as search_filtered."""
    from local.plate import to_search_like

    where: List[str] = []
    params: List[Any] = []
    if collection:
        where.append(_collection_clause(collection, ""))
    if query:
        mode, pattern = to_search_like(query)
        where.append("digits LIKE ?" if mode == "digits" else "plate_number LIKE ?")
        params.append(pattern)
    if region:
        where.append("region = ?")
        params.append(region)
    if tsc:
        where.append("tsc = ?")
        params.append(tsc)
    if letters_start:
        where.append("letters_start = ?")
        params.append(letters_start)
    if vehicle_type:
        where.append("vehicle_type = ?")
        params.append(vehicle_type)
    if price_min is not None:
        where.append("price >= ?")
        params.append(price_min)
    if price_max is not None:
        where.append("price <= ?")
        params.append(price_max)
    if only_available:
        where.append("is_available = 1")
    where_sql = (" WHERE " + " AND ".join(where)) if where else ""
    return int(await _fetchval("SELECT COUNT(*) FROM plates" + where_sql, *params))


def _feed_where(kind: str, period: str, region: Optional[str], vehicle_type: Optional[str]) -> tuple:
    """Build (where, params) over feed_events using a Python-computed time cutoff."""
    days = {"day": 1, "week": 7, "month": 30}.get(period, 1)
    where = ["event = ?", "created_at >= ?"]
    params: List[Any] = ["removed" if kind == "removed" else "new", _cutoff(days)]
    if region:
        where.append("region = ?")
        params.append(region)
    if vehicle_type:
        where.append("vehicle_type = ?")
        params.append(vehicle_type)
    return where, params


async def feed(
    kind: str, period: str, region: Optional[str] = None, vehicle_type: Optional[str] = None,
    limit: int = 15, offset: int = 0,
) -> List[Dict[str, Any]]:
    """Recently added or removed plate events within a period."""
    where, params = _feed_where(kind, period, region, vehicle_type)
    sql = (
        "SELECT plate_number, region, vehicle_type, created_at AS event_at FROM feed_events "
        "WHERE " + " AND ".join(where) + " ORDER BY created_at DESC LIMIT ? OFFSET ?"
    )
    return [dict(r) for r in await _fetch(sql, *(params + [limit, offset]))]


async def feed_count(
    kind: str, period: str, region: Optional[str] = None, vehicle_type: Optional[str] = None
) -> int:
    """Count feed events for the given filters."""
    where, params = _feed_where(kind, period, region, vehicle_type)
    return int(await _fetchval("SELECT COUNT(*) FROM feed_events WHERE " + " AND ".join(where), *params))


async def tsc_breakdown(region: Optional[str] = None, vehicle_type: Optional[str] = None) -> List[Dict[str, Any]]:
    """Per-TSC breakdown of AVAILABLE plates (count, price range, address) for a region+type."""
    where = ["p.is_available = 1"]
    params: List[Any] = []
    if region:
        where.append("p.region = ?")
        params.append(region)
    if vehicle_type:
        where.append("p.vehicle_type = ?")
        params.append(vehicle_type)
    sql = (
        "SELECT p.tsc, COUNT(*) cnt, MIN(p.price) pmin, MAX(p.price) pmax, t.address "
        "FROM plates p LEFT JOIN tsc t ON p.tsc = t.code WHERE " + " AND ".join(where)
        + " GROUP BY p.tsc, t.address ORDER BY cnt DESC"
    )
    return [dict(r) for r in await _fetch(sql, *params)]


async def plate_locations(plate_number: str) -> List[Dict[str, Any]]:
    """All rows (TSC/type/price/address) for a given plate number."""
    from local.plate import normalize_plate

    return [dict(r) for r in await _fetch(
        "SELECT p.plate_number, p.region, p.tsc, p.vehicle_type, p.price, p.is_available, "
        "p.first_seen_at, p.last_seen_at, p.removed_at, t.address AS tsc_address "
        "FROM plates p LEFT JOIN tsc t ON p.tsc = t.code "
        "WHERE p.plate_number = ? ORDER BY p.price",
        normalize_plate(plate_number),
    )]


# ── favorites ──
async def add_favorite(chat_id: int, plate_number: str) -> int:
    """Add a plate to favorites (storing digits+region); returns total holders of the plate."""
    digits = parse_plate(plate_number).get("digits")
    region = await _fetchval("SELECT region FROM plates WHERE plate_number=? LIMIT 1", plate_number)
    await _exec(
        "INSERT INTO favorites (chat_id, plate_number, digits, region, created_at) "
        "VALUES (?,?,?,?,?) ON CONFLICT DO NOTHING",
        chat_id, plate_number, digits, region, _now(),
    )
    return int(await _fetchval("SELECT COUNT(*) FROM favorites WHERE plate_number=?", plate_number))


async def favorites_combo_count(digits: Optional[str], region: Optional[str] = None) -> int:
    """How many users favorited ANY plate with this digit combination (optionally per region)."""
    if not digits:
        return 0
    sql = "SELECT COUNT(DISTINCT chat_id) FROM favorites WHERE digits=?"
    params: List[Any] = [digits]
    if region:
        sql += " AND region=?"
        params.append(region)
    return int(await _fetchval(sql, *params))


async def hunts_combo_count(digits: Optional[str], region: Optional[str] = None) -> int:
    """How many users hunt this exact digit combination (region match or all-regions hunt)."""
    if not digits:
        return 0
    sql = "SELECT COUNT(DISTINCT chat_id) FROM hunts WHERE is_active=1 AND digits_exact=?"
    params: List[Any] = [digits]
    if region:
        sql += " AND (region=? OR region IS NULL)"
        params.append(region)
    return int(await _fetchval(sql, *params))


async def remove_favorite(chat_id: int, plate_number: str) -> None:
    """Remove a plate from a user's favorites."""
    await _exec("DELETE FROM favorites WHERE chat_id=? AND plate_number=?", chat_id, plate_number)


async def is_favorite(chat_id: int, plate_number: str) -> bool:
    """Whether the plate is in the user's favorites."""
    return await _fetchval(
        "SELECT 1 FROM favorites WHERE chat_id=? AND plate_number=?", chat_id, plate_number
    ) is not None


async def favorites_count(plate_number: str) -> int:
    """How many users have this plate in favorites."""
    return int(await _fetchval("SELECT COUNT(*) FROM favorites WHERE plate_number=?", plate_number))


async def list_favorites(chat_id: int) -> List[str]:
    """A user's favorite plate numbers, newest first."""
    return [r[0] for r in await _fetch(
        "SELECT plate_number FROM favorites WHERE chat_id=? ORDER BY created_at DESC", chat_id
    )]


async def get_stats() -> Dict[str, Any]:
    """Cached aggregate counters for the main menu / stats screen (heavy; memoised ~90s)."""
    return await _memo("stats", 300, _get_stats_raw)


async def _get_stats_raw() -> Dict[str, Any]:
    row = dict(await _fetchrow(
        "SELECT COUNT(*) total, "
        "SUM(CASE WHEN is_available=1 THEN 1 ELSE 0 END) available, "
        "MIN(CASE WHEN is_available=1 THEN price END) price_min, "
        "MAX(CASE WHEN is_available=1 THEN price END) price_max FROM plates"
    ))
    row["by_region"] = [dict(r) for r in await _fetch(
        "SELECT region, COUNT(*) c FROM plates WHERE is_available=1 GROUP BY region ORDER BY c DESC LIMIT 8"
    )]
    row["by_type"] = [dict(r) for r in await _fetch(
        "SELECT vehicle_type t, COUNT(*) c FROM plates WHERE is_available=1 AND vehicle_type IS NOT NULL "
        "GROUP BY vehicle_type ORDER BY c DESC"
    )]
    row["last_scan"] = await _fetchval("SELECT value FROM meta WHERE key='last_scan'")
    return row


async def set_tsc_address(
    code: str, address: Optional[str], city: Optional[str],
    lat: Optional[float] = None, lon: Optional[float] = None, name: Optional[str] = None,
) -> None:
    """Fill address/city/coords for a TSC code from the directory builder."""
    await _exec(
        "INSERT INTO tsc (code, address, city, lat, lon, name) VALUES (?,?,?,?,?,?) "
        "ON CONFLICT (code) DO UPDATE SET address=COALESCE(excluded.address, tsc.address), "
        "city=COALESCE(excluded.city, tsc.city), lat=COALESCE(excluded.lat, tsc.lat), "
        "lon=COALESCE(excluded.lon, tsc.lon), name=COALESCE(excluded.name, tsc.name)",
        code, address, city, lat, lon, name,
    )


async def tsc_address(code: str) -> Optional[str]:
    """Return a TSC's address string if known."""
    return await _fetchval("SELECT address FROM tsc WHERE code=? AND address IS NOT NULL", code)


# ── admins / reports / broadcast ──
async def is_admin(chat_id: int) -> bool:
    """True for the super-admin (config) or any registered admin."""
    if config.ADMIN_CHAT_ID and chat_id == config.ADMIN_CHAT_ID:
        return True
    return await _fetchval("SELECT 1 FROM admins WHERE chat_id=?", chat_id) is not None


async def add_admin(chat_id: int, added_by: int) -> None:
    """Register a new admin."""
    await _exec(
        "INSERT INTO admins (chat_id, added_by, created_at) VALUES (?,?,?) ON CONFLICT DO NOTHING",
        chat_id, added_by, _now(),
    )


async def remove_admin(chat_id: int) -> None:
    """Remove an admin."""
    await _exec("DELETE FROM admins WHERE chat_id=?", chat_id)


async def list_admins() -> List[Dict[str, Any]]:
    """List registered (non-super) admins."""
    return [dict(r) for r in await _fetch("SELECT * FROM admins ORDER BY created_at")]


async def add_report(chat_id: int, username: Optional[str], text: str) -> int:
    """Store an error report from a user."""
    return int(await _fetchval(
        "INSERT INTO error_reports (chat_id, username, text, created_at) VALUES (?,?,?,?) RETURNING id",
        chat_id, username, text, _now(),
    ))


async def recent_reports(limit: int = 15) -> List[Dict[str, Any]]:
    """Most recent error reports."""
    return [dict(r) for r in await _fetch(
        "SELECT * FROM error_reports ORDER BY created_at DESC LIMIT ?", limit
    )]


async def all_user_ids() -> List[int]:
    """All real user chat ids (for broadcast; bots excluded)."""
    return [int(r[0]) for r in await _fetch("SELECT chat_id FROM users WHERE COALESCE(is_bot,0)=0")]


async def admin_stats() -> Dict[str, Any]:
    """Aggregate counts for the admin panel."""
    async def one(sql: str) -> int:
        return int(await _fetchval(sql))
    return {
        "users": await one("SELECT COUNT(*) FROM users WHERE COALESCE(is_bot,0)=0"),
        "bots": await one("SELECT COUNT(*) FROM users WHERE is_bot=1"),
        "pro_users": await one("SELECT COUNT(*) FROM users WHERE plan='pro' AND COALESCE(is_bot,0)=0"),
        "hunts": await one("SELECT COUNT(*) FROM hunts"),
        "favorites": await one("SELECT COUNT(*) FROM favorites"),
        "plates": await one("SELECT COUNT(*) FROM plates"),
        "reports": await one("SELECT COUNT(*) FROM error_reports"),
    }


async def add_notif_message(chat_id: int, message_id: int) -> None:
    """Remember a notification message id so /start can preserve it during a wipe."""
    await _exec(
        "INSERT INTO notif_messages (chat_id, message_id, created_at) VALUES (?,?,?)",
        chat_id, message_id, _now(),
    )


async def notif_message_ids(chat_id: int) -> List[int]:
    """Notification message ids for a chat."""
    return [int(r[0]) for r in await _fetch(
        "SELECT message_id FROM notif_messages WHERE chat_id=?", chat_id
    )]


# ── demo bots ──
async def bot_count() -> int:
    """Number of demo-bot users."""
    return int(await _fetchval("SELECT COUNT(*) FROM users WHERE is_bot=1"))


async def _beautiful_pool(conn: asyncpg.Connection, limit: int = 25000) -> List[Dict[str, Any]]:
    """Large, diverse sample of available 'attractive' plates for bots to like/monitor."""
    kinds = ["same", "mirror", "pairs", "abab", "round", "low"]
    clause = " OR ".join(f"({_collection_clause(k)})" for k in kinds)
    clause += " OR (length(digits)=4 AND digits LIKE '_000')"
    rows = await conn.fetch(
        f"SELECT plate_number, digits, region, vehicle_type FROM plates "
        f"WHERE is_available=1 AND digits IS NOT NULL AND ({clause}) "
        f"ORDER BY random() LIMIT $1",
        limit,
    )
    return [dict(r) for r in rows]


async def create_bots(n: int, fav_range=(20, 80), hunt_range=(15, 60)) -> int:
    """Create ``n`` demo-bot users, each with random beautiful favorites + monitorings."""
    now = _now()
    pool = await _get_pool()
    async with pool.acquire() as conn:
        bpool = await _beautiful_pool(conn)
        if not bpool:
            return 0
        digit_pool = list({p["digits"] for p in bpool if p["digits"]})
        min_id = await conn.fetchval("SELECT MIN(chat_id) FROM users WHERE is_bot=1")
        next_id = (min_id - 1) if min_id is not None else -1_000_000_001
        created = 0
        for _ in range(n):
            bid = next_id
            next_id -= 1
            await conn.execute(
                "INSERT INTO users (chat_id, username, created_at, is_bot, shared) "
                "VALUES ($1,$2,$3,1,1) ON CONFLICT DO NOTHING",
                bid, f"bot_{abs(bid) % 1000000}", now,
            )
            favs = random.sample(bpool, min(random.randint(*fav_range), len(bpool)))
            await conn.executemany(
                "INSERT INTO favorites (chat_id, plate_number, digits, region, created_at) "
                "VALUES ($1,$2,$3,$4,$5) ON CONFLICT DO NOTHING",
                [(bid, f["plate_number"], f["digits"], f["region"], now) for f in favs],
            )
            hcombos = random.sample(digit_pool, min(random.randint(*hunt_range), len(digit_pool)))
            await conn.executemany(
                "INSERT INTO hunts (chat_id, name, match_type, pattern, digits_exact, created_at) "
                "VALUES ($1,$2,'digits',$3,$4,$5)",
                [(bid, d, d, d, now) for d in hcombos],
            )
            created += 1
        return created


async def delete_bots(n: int) -> int:
    """Delete ``n`` random demo bots and their data."""
    ids = [int(r[0]) for r in await _fetch(
        "SELECT chat_id FROM users WHERE is_bot=1 ORDER BY random() LIMIT ?", n
    )]
    if not ids:
        return 0
    for tbl in ("favorites", "hunts", "search_log", "users"):
        await _exec(f"DELETE FROM {tbl} WHERE chat_id = ANY($1::bigint[])", ids)
    return len(ids)


async def delete_all_bots() -> int:
    """Delete every demo bot and its data."""
    cnt = int(await _fetchval("SELECT COUNT(*) FROM users WHERE is_bot=1"))
    for tbl in ("favorites", "hunts", "search_log"):
        await _exec(f"DELETE FROM {tbl} WHERE chat_id IN (SELECT chat_id FROM users WHERE is_bot=1)")
    await _exec("DELETE FROM users WHERE is_bot=1")
    return cnt


# ── app account linking (Telegram ↔ app) ──
async def link_create(code: str, token: str) -> None:
    """Start an app↔Telegram link (status pending until the bot binds a chat_id)."""
    await _exec("INSERT INTO app_link (code, token, status, created_at) VALUES (?,?, 'pending', ?) "
                "ON CONFLICT (code) DO NOTHING", code, token, _now())


async def link_bind(code: str, chat_id: int) -> bool:
    """Bind a pending link code to a Telegram chat_id (called from the bot). True if bound."""
    return await _fetchval(
        "UPDATE app_link SET chat_id=?, status='linked' WHERE code=? AND status='pending' RETURNING code",
        chat_id, code,
    ) is not None


async def link_status(code: str) -> Optional[Dict[str, Any]]:
    """Status of a link code: {status, chat_id, token}."""
    row = await _fetchrow("SELECT status, chat_id, token FROM app_link WHERE code=?", code)
    return dict(row) if row else None


async def token_chat(token: str) -> Optional[int]:
    """Resolve an app token to its linked chat_id (None if not linked)."""
    return await _fetchval("SELECT chat_id FROM app_link WHERE token=? AND status='linked'", token)


async def create_anon_account(token: str, chat_id: int) -> None:
    """Create an anonymous app account (token already 'linked' to a synthetic chat_id)."""
    await _exec("INSERT INTO app_link (code, chat_id, token, status, created_at) "
                "VALUES (?,?,?, 'linked', ?) ON CONFLICT (code) DO NOTHING",
                token, chat_id, token, _now())


async def merge_account(from_chat: int, to_chat: int) -> None:
    """Move favorites + monitorings from one account into another (used when linking)."""
    if from_chat == to_chat:
        return
    await _exec(
        "INSERT INTO favorites (chat_id, plate_number, digits, region, created_at) "
        "SELECT ?, plate_number, digits, region, created_at FROM favorites WHERE chat_id=? "
        "ON CONFLICT DO NOTHING", to_chat, from_chat,
    )
    await _exec("DELETE FROM favorites WHERE chat_id=?", from_chat)
    await _exec("UPDATE hunts SET chat_id=? WHERE chat_id=?", to_chat, from_chat)


async def get_meta(key: str) -> Optional[str]:
    """Read a meta value, or None."""
    return await _fetchval("SELECT value FROM meta WHERE key=?", key)


async def set_meta(key: str, value: str) -> None:
    """Upsert a meta key/value."""
    await _exec(
        "INSERT INTO meta (key, value) VALUES (?,?) ON CONFLICT (key) DO UPDATE SET value=excluded.value",
        key, value,
    )


# ── users & hunts ──
async def ensure_user(chat_id: int, username: Optional[str]) -> None:
    """Create the user row if absent."""
    await _exec(
        "INSERT INTO users (chat_id, username, created_at) VALUES (?,?,?) "
        "ON CONFLICT (chat_id) DO UPDATE SET username=excluded.username",
        chat_id, username, _now(),
    )


async def get_user(chat_id: int) -> Optional[Dict[str, Any]]:
    """Fetch a user row by chat id."""
    row = await _fetchrow("SELECT * FROM users WHERE chat_id=?", chat_id)
    return dict(row) if row else None


async def grant_pro(chat_id: int, days: int) -> None:
    """Grant or extend PRO by ``days`` (from the later of now / current expiry)."""
    user = await get_user(chat_id)
    base = dt.datetime.now(dt.timezone.utc)
    if user and user.get("plan_until"):
        try:
            cur = dt.datetime.fromisoformat(user["plan_until"])
            if cur > base:
                base = cur
        except ValueError:
            pass
    until = (base + dt.timedelta(days=days)).isoformat()
    await _exec("UPDATE users SET plan='pro', plan_until=? WHERE chat_id=?", until, chat_id)


async def set_referrer(chat_id: int, referrer_id: int) -> Optional[Dict[str, Any]]:
    """Attribute a new user to a referrer (once) and reward the referrer."""
    if chat_id == referrer_id:
        return None
    user = await get_user(chat_id)
    if user and user.get("referred_by"):
        return None
    ref = await get_user(referrer_id)
    if not ref:
        return None
    invited = (ref.get("invited_count") or 0) + 1
    await _exec("UPDATE users SET referred_by=? WHERE chat_id=?", referrer_id, chat_id)
    await _exec("UPDATE users SET invited_count=? WHERE chat_id=?", invited, referrer_id)
    pro_granted = 0
    if invited == PRO_INVITE_THRESHOLD:
        await grant_pro(referrer_id, PRO_DAYS_FOR_INVITES)
        pro_granted = PRO_DAYS_FOR_INVITES
    return {"invited_count": invited, "pro_days": pro_granted}


async def mark_shared(chat_id: int) -> bool:
    """Grant the one-time share bonus. Returns True only the first time."""
    user = await get_user(chat_id)
    if not user or user.get("shared"):
        return False
    await _exec("UPDATE users SET shared=1 WHERE chat_id=?", chat_id)
    return True


async def set_phone(chat_id: int, phone: str) -> bool:
    """Store the user's phone and grant the one-time share bonus. Returns True if newly granted."""
    user = await get_user(chat_id)
    newly = bool(user) and not user.get("shared")
    await _exec("UPDATE users SET phone=?, shared=1 WHERE chat_id=?", phone, chat_id)
    return newly


async def log_search(chat_id: int, username: Optional[str], summary: str) -> None:
    """Record what a user searched (for admin analytics)."""
    await _exec(
        "INSERT INTO search_log (chat_id, username, summary, created_at) VALUES (?,?,?,?)",
        chat_id, username, summary, _now(),
    )


async def recent_searches(limit: int = 15) -> List[Dict[str, Any]]:
    """Most recent searches across all users."""
    return [dict(r) for r in await _fetch(
        "SELECT chat_id, username, summary, created_at FROM search_log ORDER BY created_at DESC LIMIT ?",
        limit,
    )]


async def top_searches(limit: int = 10) -> List[Dict[str, Any]]:
    """Most frequent search summaries."""
    return [dict(r) for r in await _fetch(
        "SELECT summary, COUNT(*) c FROM search_log GROUP BY summary ORDER BY c DESC LIMIT ?", limit
    )]


async def recent_users(limit: int = 15) -> List[Dict[str, Any]]:
    """Most recently registered users with key fields."""
    return [dict(r) for r in await _fetch(
        "SELECT chat_id, username, phone, plan, invited_count, created_at, is_bot "
        "FROM users WHERE COALESCE(is_bot,0)=0 ORDER BY created_at DESC LIMIT ?", limit,
    )]


async def user_overview(chat_id: int) -> Dict[str, Any]:
    """Full profile of one user for the admin panel."""
    u = await _fetchrow("SELECT * FROM users WHERE chat_id=?", chat_id)
    user = dict(u) if u else {"chat_id": chat_id}
    user["hunts"] = int(await _fetchval("SELECT COUNT(*) FROM hunts WHERE chat_id=?", chat_id))
    user["favorites"] = int(await _fetchval("SELECT COUNT(*) FROM favorites WHERE chat_id=?", chat_id))
    user["searches"] = int(await _fetchval("SELECT COUNT(*) FROM search_log WHERE chat_id=?", chat_id))
    user["recent_searches"] = [dict(r) for r in await _fetch(
        "SELECT summary, created_at FROM search_log WHERE chat_id=? ORDER BY created_at DESC LIMIT 5",
        chat_id,
    )]
    user["hunt_list"] = [dict(r) for r in await _fetch(
        "SELECT name, match_type FROM hunts WHERE chat_id=? ORDER BY created_at DESC LIMIT 5", chat_id
    )]
    return user


async def find_user_by_identifier(identifier: str) -> Optional[Dict[str, Any]]:
    """Resolve a user by numeric chat_id or @username (case-insensitive)."""
    ident = identifier.strip().lstrip("@")
    if ident.lstrip("-").isdigit():
        row = await _fetchrow("SELECT * FROM users WHERE chat_id=?", int(ident))
    else:
        row = await _fetchrow("SELECT * FROM users WHERE lower(username)=lower(?)", ident)
    return dict(row) if row else None


async def new_users_count(days: int = 1) -> int:
    """How many users registered in the last N days."""
    return int(await _fetchval(
        "SELECT COUNT(*) FROM users WHERE COALESCE(is_bot,0)=0 AND created_at >= ?", _cutoff(days)
    ))


async def active_hunt_count(chat_id: int) -> int:
    """Number of hunts the user has."""
    return int(await _fetchval("SELECT COUNT(*) FROM hunts WHERE chat_id=?", chat_id))


async def hunt_limit(chat_id: int) -> int:
    """Max hunts: huge for PRO, else base + share bonus + (friends // FRIENDS_PER_HUNT)."""
    user = await get_user(chat_id)
    if is_pro(user):
        return 10_000
    if not user:
        return BASE_FREE_HUNTS
    bonus = (SHARE_BONUS_HUNTS if user.get("shared") else 0)
    bonus += (user.get("invited_count") or 0) // FRIENDS_PER_HUNT
    return BASE_FREE_HUNTS + bonus


async def check_search_quota(chat_id: int) -> Dict[str, Any]:
    """Return {allowed, used, limit, pro} for today's searches (does not consume)."""
    user = await get_user(chat_id)
    if is_pro(user):
        return {"allowed": True, "used": 0, "limit": None, "pro": True}
    today = dt.date.today().isoformat()
    used = (user.get("searches_today") or 0) if user and user.get("searches_date") == today else 0
    return {"allowed": used < SEARCH_LIMIT_PER_DAY, "used": used, "limit": SEARCH_LIMIT_PER_DAY, "pro": False}


async def consume_search(chat_id: int) -> None:
    """Increment today's search counter (resetting the day if needed)."""
    today = dt.date.today().isoformat()
    row = await _fetchrow("SELECT searches_today, searches_date FROM users WHERE chat_id=?", chat_id)
    used = (row[0] or 0) if row and row[1] == today else 0
    await _exec(
        "UPDATE users SET searches_today=?, searches_date=? WHERE chat_id=?", used + 1, today, chat_id
    )


async def add_hunt(chat_id: int, fields: Dict[str, Any]) -> int:
    """Insert a hunt for a user, returns its id."""
    return int(await _fetchval(
        "INSERT INTO hunts (chat_id, name, match_type, pattern, letters_start, letters_end, "
        "digits_exact, digits_contains, digits_mask, region, vehicle_type, price_min, price_max, created_at) "
        "VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) RETURNING id",
        chat_id, fields.get("name"), fields["match_type"], fields.get("pattern"),
        fields.get("letters_start"), fields.get("letters_end"), fields.get("digits_exact"),
        fields.get("digits_contains"), fields.get("digits_mask"), fields.get("region"),
        fields.get("vehicle_type"), fields.get("price_min"), fields.get("price_max"), _now(),
    ))


async def count_hunt_matches(h: Dict[str, Any]) -> int:
    """How many AVAILABLE plates currently satisfy this hunt."""
    where, params = _hunt_criteria(h)
    sql = "SELECT COUNT(*) FROM plates WHERE is_available=1 AND " + " AND ".join(where)
    return int(await _fetchval(sql, *params))


async def list_hunt_matches(h: Dict[str, Any], limit: int = 15, offset: int = 0) -> List[Dict[str, Any]]:
    """Available plates satisfying this hunt (with TSC address), cheapest first."""
    where, params = _hunt_criteria(h, alias="p.")
    sql = (
        "SELECT p.plate_number, p.region, p.tsc, p.vehicle_type, p.price, p.is_available, "
        "t.address AS tsc_address FROM plates p LEFT JOIN tsc t ON p.tsc=t.code "
        "WHERE p.is_available=1 AND " + " AND ".join(where)
        + " ORDER BY p.price IS NULL, p.price LIMIT ? OFFSET ?"
    )
    return [dict(r) for r in await _fetch(sql, *(params + [limit, offset]))]


async def hunt_changes_24h(h: Dict[str, Any]) -> tuple:
    """Return (new, removed) plate counts matching the hunt in the last 24 hours."""
    where, params = _hunt_criteria(h)
    crit = " AND ".join(where)
    cutoff = _cutoff(1)
    new = int(await _fetchval(
        f"SELECT COUNT(*) FROM plates WHERE {crit} AND first_seen_at >= ?", *(params + [cutoff])
    ))
    removed = int(await _fetchval(
        f"SELECT COUNT(*) FROM plates WHERE {crit} AND removed_at >= ?", *(params + [cutoff])
    ))
    return new, removed


async def get_hunt(chat_id: int, hunt_id: int) -> Optional[Dict[str, Any]]:
    """Fetch one hunt owned by the user."""
    row = await _fetchrow("SELECT * FROM hunts WHERE id=? AND chat_id=?", hunt_id, chat_id)
    return dict(row) if row else None


async def list_hunts(chat_id: int) -> List[Dict[str, Any]]:
    """List a user's hunts."""
    return [dict(r) for r in await _fetch(
        "SELECT * FROM hunts WHERE chat_id=? ORDER BY created_at DESC", chat_id
    )]


async def toggle_hunt(chat_id: int, hunt_id: int) -> bool:
    """Flip a hunt's is_active flag. Returns True if a row was changed."""
    return await _fetchval(
        "UPDATE hunts SET is_active = 1 - is_active WHERE id=? AND chat_id=? RETURNING id",
        hunt_id, chat_id,
    ) is not None


async def delete_hunt(chat_id: int, hunt_id: int) -> bool:
    """Delete a hunt the user owns. Returns True if deleted."""
    return await _fetchval(
        "DELETE FROM hunts WHERE id=? AND chat_id=? RETURNING id", hunt_id, chat_id
    ) is not None
